`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 19.01.2026 17:09:14
// Design Name: 
// Module Name: dadda_16
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////
module fa(
    input a,
    input b,
    input cin,
    output sum,
    output cout
);

    assign sum = a^b^cin;
    assign cout = (a&b)|(b&cin)|(cin&a);
    
endmodule

module ha(
    input a,
    input b,
    output sum,
    output cout
);

    assign sum = a^b;
    assign cout = (a&b);
    
endmodule

module dadda_16(
    input [15:0] a,
    input [15:0] b,
    output [31:0] y
);
    
    wire [15:0] p0, p1,p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15;   //Initial partial product
    wire [31:0] in1, in2; 
    
    //All sum and carry generated by half/full adders
    wire s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, 
         s21, s22, s23, s24, s25, s26, s27, s28, s29, s30, s31, s32, s33, s34, s35, s36, s37, s38, s39, s40, 
         s41, s42, s43, s44, s45, s46, s47, s48, s49, s50, s51, s52, s53, s54, s55, s56, s57, s58, s59, s60, 
         s61, s62, s63, s64, s65, s66, s67, s68, s69, s70, s71, s72, s73, s74, s75, s76, s77, s78, s79, s80, 
         s81, s82, s83, s84, s85, s86, s87, s88, s89, s90, s91, s92, s93, s94, s95, s96, s97, s98, s99, s100, 
         s101, s102, s103, s104, s105, s106, s107, s108, s109, s110, s111, s112, s113, s114, s115, s116, s117, 
         s118, s119, s120, s121, s122, s123, s124, s125, s126, s127, s128, s129, s130, s131, s132, s133, s134, 
         s135, s136, s137, s138, s139, s140, s141, s142, s143, s144, s145, s146, s147, s148, s149, s150, s151, 
         s152, s153, s154, s155, s156, s157, s158, s159, s160, s161, s162, s163, s164, s165, s166, s167, s168, 
         s169, s170, s171, s172, s173, s174, s175, s176, s177, s178, s179, s180, s181, s182, s183, s184, s185, 
         s186, s187, s188, s189, s190, s191, s192, s193, s194, s195, s196, s197, s198, s199, s200, s201, s202, 
         s203, s204, s205, s206, s207, s208, s209, s210;
    wire c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, 
         c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, 
         c41, c42, c43, c44, c45, c46, c47, c48, c49, c50, c51, c52, c53, c54, c55, c56, c57, c58, c59, c60, 
         c61, c62, c63, c64, c65, c66, c67, c68, c69, c70, c71, c72, c73, c74, c75, c76, c77, c78, c79, c80, 
         c81, c82, c83, c84, c85, c86, c87, c88, c89, c90, c91, c92, c93, c94, c95, c96, c97, c98, c99, c100, 
         c101, c102, c103, c104, c105, c106, c107, c108, c109, c110, c111, c112, c113, c114, c115, c116, c117, 
         c118, c119, c120, c121, c122, c123, c124, c125, c126, c127, c128, c129, c130, c131, c132, c133, c134, 
         c135, c136, c137, c138, c139, c140, c141, c142, c143, c144, c145, c146, c147, c148, c149, c150, c151, 
         c152, c153, c154, c155, c156, c157, c158, c159, c160, c161, c162, c163, c164, c165, c166, c167, c168, 
         c169, c170, c171, c172, c173, c174, c175, c176, c177, c178, c179, c180, c181, c182, c183, c184, c185, 
         c186, c187, c188, c189, c190, c191, c192, c193, c194, c195, c196, c197, c198, c199, c200, c201, c202, 
         c203, c204, c205, c206, c207, c208, c209, c210;

    assign p0 = {1'b1, ~(b[0]&a[15]), (a[14:0]&{15{b[0]}}) };
    assign p1 = {~(b[1]&a[15]), (a[14:0]&{15{b[1]}}) };
    assign p2 = {~(b[2]&a[15]), (a[14:0]&{15{b[2]}}) };
    assign p3 = {~(b[3]&a[15]), (a[14:0]&{15{b[3]}}) };
    assign p4 = {~(b[4]&a[15]), (a[14:0]&{15{b[4]}}) };
    assign p5 = {~(b[5]&a[15]), (a[14:0]&{15{b[5]}}) };
    assign p6 = {~(b[6]&a[15]), (a[14:0]&{15{b[6]}}) };
    assign p7 = {~(b[7]&a[15]), (a[14:0]&{15{b[7]}}) };
    assign p8 = {~(b[8]&a[15]), (a[14:0]&{15{b[8]}}) };
    assign p9 = {~(b[9]&a[15]), (a[14:0]&{15{b[9]}}) };
    assign p10 = {~(b[10]&a[15]), (a[14:0]&{15{b[10]}}) };
    assign p11 = {~(b[11]&a[15]), (a[14:0]&{15{b[11]}}) };
    assign p12 = {~(b[12]&a[15]), (a[14:0]&{15{b[12]}}) };
    assign p13 = {~(b[13]&a[15]), (a[14:0]&{15{b[13]}}) };
    assign p14 = {~(b[14]&a[15]), (a[14:0]&{15{b[14]}}) };
    assign p15 = {1'b1, (b[15]&a[15]), ~(a[14:0]&{15{b[15]}}) };
    
    //Stage 1 reduction - Dadda
    ha h1 ( .a(p0[13]), .b(p1[12]), .sum(s1), .cout(c1) );
    fa f1 ( .a(p0[14]), .b(p1[13]), .cin(p2[12]), .sum(s2), .cout(c2) );
    ha h2 ( .a(p3[11]), .b(p4[10]), .sum(s3), .cout(c3) );
    fa f2 ( .a(p0[15]), .b(p1[14]), .cin(p2[13]), .sum(s4), .cout(c4) );
    fa f3 ( .a(p3[12]), .b(p4[11]), .cin(p5[10]), .sum(s5), .cout(c5) );
    ha h3 ( .a(p6[9]), .b(p7[8]), .sum(s6), .cout(c6) );
    fa f4 ( .a(1'b1), .b(p1[15]), .cin(p2[14]), .sum(s7), .cout(c7) );
    fa f5 ( .a(p3[13]), .b(p4[12]), .cin(p5[11]), .sum(s8), .cout(c8) );
    fa f6 ( .a(p6[10]), .b(p7[9]), .cin(p8[8]), .sum(s9), .cout(c9) );
    fa f7 ( .a(p2[15]), .b(p3[14]), .cin(p4[13]), .sum(s10), .cout(c10) );
    fa f8 ( .a(p5[12]), .b(p6[11]), .cin(p7[10]), .sum(s11), .cout(c11) );
    fa f9 ( .a(p3[15]), .b(p4[14]), .cin(p5[13]), .sum(s12), .cout(c12) );
    
    
    //Stage 2 reduction - Dadda
    ha h4  ( .a(p0[9]),  .b(p1[8]),  .sum(s13), .cout(c13) );
    fa f10 ( .a(p0[10]), .b(p1[9]),  .cin(p2[8]),  .sum(s14), .cout(c14) );
    ha h5  ( .a(p3[7]),  .b(p4[6]),  .sum(s15), .cout(c15) );
    fa f11 ( .a(p0[11]), .b(p1[10]), .cin(p2[9]),  .sum(s16), .cout(c16) );
    fa f12 ( .a(p3[8]),  .b(p4[7]),  .cin(p5[6]),  .sum(s17), .cout(c17) );
    ha h6  ( .a(p6[5]),  .b(p7[4]),  .sum(s18), .cout(c18) );
    fa f13 ( .a(p0[12]), .b(p1[11]), .cin(p2[10]), .sum(s19), .cout(c19) );
    fa f14 ( .a(p3[9]),  .b(p4[8]),  .cin(p5[7]),  .sum(s20), .cout(c20) );
    fa f15 ( .a(p6[6]),  .b(p7[5]),  .cin(p8[4]),  .sum(s21), .cout(c21) );
    ha h7  ( .a(p9[3]),  .b(p10[2]), .sum(s22), .cout(c22) );
    fa f16 ( .a(s1),     .b(p2[11]), .cin(p3[10]), .sum(s23), .cout(c23) );
    fa f17 ( .a(p4[9]),  .b(p5[8]),  .cin(p6[7]),  .sum(s24), .cout(c24) );
    fa f18 ( .a(p7[6]),  .b(p8[5]),  .cin(p9[4]),  .sum(s25), .cout(c25) );
    fa f19 ( .a(p10[3]), .b(p11[2]), .cin(p12[1]), .sum(s26), .cout(c26) );
    fa f20 ( .a(c1),     .b(s2),     .cin(s3),     .sum(s27), .cout(c27) );
    fa f21 ( .a(p5[9]),  .b(p6[8]),  .cin(p7[7]),  .sum(s28), .cout(c28) );
    fa f22 ( .a(p8[6]),  .b(p9[5]),  .cin(p10[4]), .sum(s29), .cout(c29) );
    fa f23 ( .a(p11[3]), .b(p12[2]), .cin(p13[1]), .sum(s30), .cout(c30) );
    fa f24 ( .a(c2),     .b(c3),     .cin(s4),     .sum(s31), .cout(c31) );
    fa f25 ( .a(s5),     .b(s6),     .cin(p8[7]),  .sum(s32), .cout(c32) );
    fa f26 ( .a(p9[6]),  .b(p10[5]), .cin(p11[4]), .sum(s33), .cout(c33) );
    fa f27 ( .a(p12[3]), .b(p13[2]), .cin(p14[1]), .sum(s34), .cout(c34) );
    fa f28 ( .a(c4),     .b(c5),     .cin(c6),     .sum(s35), .cout(c35) );
    fa f29 ( .a(s7),     .b(s8),     .cin(s9),     .sum(s36), .cout(c36) );
    fa f30 ( .a(p9[7]),  .b(p10[6]), .cin(p11[5]), .sum(s37), .cout(c37) );
    fa f31 ( .a(p12[4]), .b(p13[3]), .cin(p14[2]), .sum(s38), .cout(c38) );
    fa f32 ( .a(c7),     .b(c8),     .cin(c9),     .sum(s39), .cout(c39) );
    fa f33 ( .a(s10),    .b(s11),    .cin(p8[9]),  .sum(s40), .cout(c40) );
    fa f34 ( .a(p9[8]),  .b(p10[7]), .cin(p11[6]), .sum(s41), .cout(c41) );
    fa f35 ( .a(p12[5]), .b(p13[4]), .cin(p14[3]), .sum(s42), .cout(c42) );
    fa f36 ( .a(c10),    .b(c11),    .cin(s12),    .sum(s43), .cout(c43) );
    fa f37 ( .a(p6[12]), .b(p7[11]), .cin(p8[10]), .sum(s44), .cout(c44) );
    fa f38 ( .a(p9[9]),  .b(p10[8]), .cin(p11[7]), .sum(s45), .cout(c45) );
    fa f39 ( .a(p12[6]), .b(p13[5]), .cin(p14[4]), .sum(s46), .cout(c46) );
    fa f40 ( .a(c12),    .b(p4[15]),  .cin(p5[14]),  .sum(s47), .cout(c47) );
    fa f41 ( .a(p6[13]), .b(p7[12]),  .cin(p8[11]),  .sum(s48), .cout(c48) );
    fa f42 ( .a(p9[10]), .b(p10[9]),  .cin(p11[8]),  .sum(s49), .cout(c49) );
    fa f43 ( .a(p12[7]), .b(p13[6]),  .cin(p14[5]),  .sum(s50), .cout(c50) );
    fa f44 ( .a(p5[15]), .b(p6[14]),  .cin(p7[13]),  .sum(s51), .cout(c51) );
    fa f45 ( .a(p8[12]), .b(p9[11]),  .cin(p10[10]), .sum(s52), .cout(c52) );
    fa f46 ( .a(p11[9]), .b(p12[8]),  .cin(p13[7]),  .sum(s53), .cout(c53) );
    fa f47 ( .a(p6[15]), .b(p7[14]),  .cin(p8[13]),  .sum(s54), .cout(c54) );
    fa f48 ( .a(p9[12]), .b(p10[11]), .cin(p11[10]), .sum(s55), .cout(c55) );
    fa f49 ( .a(p7[15]), .b(p8[14]),  .cin(p9[13]),  .sum(s56), .cout(c56) );
    
    //Stage 3 reduction - Dadda
    ha h8   ( .a(p0[6]),  .b(p1[5]),  .sum(s57), .cout(c57) );
    fa f50  ( .a(p0[7]),  .b(p1[6]),  .cin(p2[5]),  .sum(s58), .cout(c58) );
    ha h9   ( .a(p3[4]),  .b(p4[3]),  .sum(s59), .cout(c59) );
    fa f51  ( .a(p0[8]),  .b(p1[7]),  .cin(p2[6]),  .sum(s60), .cout(c60) );
    fa f52  ( .a(p3[5]),  .b(p4[4]),  .cin(p5[3]),  .sum(s61), .cout(c61) );
    ha h10  ( .a(p6[2]),  .b(p7[1]),  .sum(s62), .cout(c62) );
    fa f53  ( .a(s13),    .b(p2[7]),  .cin(p3[6]),  .sum(s63), .cout(c63) );
    fa f54  ( .a(p4[5]),  .b(p5[4]),  .cin(p6[3]),  .sum(s64), .cout(c64) );
    fa f55  ( .a(p7[2]),  .b(p8[1]),  .cin(p9[0]),  .sum(s65), .cout(c65) );
    fa f56  ( .a(c13),    .b(s14),    .cin(s15),    .sum(s66), .cout(c66) );
    fa f57  ( .a(p5[5]),  .b(p6[4]),  .cin(p7[3]),  .sum(s67), .cout(c67) );
    fa f58  ( .a(p8[2]),  .b(p9[1]),  .cin(p10[0]), .sum(s68), .cout(c68) );
    fa f59  ( .a(c14),    .b(c15),    .cin(s16),    .sum(s69), .cout(c69) );
    fa f60  ( .a(s17),    .b(s18),    .cin(p8[3]),  .sum(s70), .cout(c70) );
    fa f61  ( .a(p9[2]),  .b(p10[1]), .cin(p11[0]), .sum(s71), .cout(c71) );
    fa f62  ( .a(c16),    .b(c17),    .cin(c18),    .sum(s72), .cout(c72) );
    fa f63  ( .a(s19),    .b(s20),    .cin(s21),    .sum(s73), .cout(c73) );
    fa f64  ( .a(s22),    .b(p11[1]), .cin(p12[0]), .sum(s74), .cout(c74) );
    fa f65  ( .a(c19),    .b(c20),    .cin(c21),    .sum(s75), .cout(c75) );
    fa f66  ( .a(c22),    .b(s23),    .cin(s24),    .sum(s76), .cout(c76) );
    fa f67  ( .a(s25),    .b(s26),    .cin(p13[0]), .sum(s77), .cout(c77) );
    fa f68  ( .a(c23),    .b(c24),    .cin(c25),    .sum(s78), .cout(c78) );
    fa f69  ( .a(c26),    .b(s27),    .cin(s28),    .sum(s79), .cout(c79) );
    fa f70  ( .a(s29),    .b(s30),    .cin(p14[0]), .sum(s80), .cout(c80) );
    fa f71  ( .a(c27),    .b(c28),    .cin(c29),    .sum(s81), .cout(c81) );
    fa f72  ( .a(c30),    .b(s31),    .cin(s32),    .sum(s82), .cout(c82) );
    fa f73  ( .a(s33),    .b(s34),    .cin(p15[0]), .sum(s83), .cout(c83) );
    fa f74  ( .a(c31),    .b(c32),    .cin(c33),    .sum(s84), .cout(c84) );
    fa f75  ( .a(c34),    .b(s35),    .cin(s36),    .sum(s85), .cout(c85) );
    fa f76  ( .a(s37),    .b(s38),    .cin(p15[1]), .sum(s86), .cout(c86) );
    fa f77  ( .a(c35),    .b(c36),    .cin(c37),    .sum(s87), .cout(c87) );
    fa f78  ( .a(c38),    .b(s39),    .cin(s40),    .sum(s88), .cout(c88) );
    fa f79  ( .a(s41),    .b(s42),    .cin(p15[2]), .sum(s89), .cout(c89) );
    fa f80  ( .a(c39),    .b(c40),    .cin(c41),    .sum(s90), .cout(c90) );
    fa f81  ( .a(c42),    .b(s43),    .cin(s44),    .sum(s91), .cout(c91) );
    fa f82  ( .a(s45),    .b(s46),    .cin(p15[3]), .sum(s92), .cout(c92) );
    fa f83  ( .a(c43),    .b(c44),    .cin(c45),    .sum(s93), .cout(c93) );
    fa f84  ( .a(c46),    .b(s47),    .cin(s48),    .sum(s94), .cout(c94) );
    fa f85  ( .a(s49),    .b(s50),    .cin(p15[4]), .sum(s95), .cout(c95) );
    fa f86  ( .a(c47),    .b(c48),    .cin(c49),    .sum(s96), .cout(c96) );
    fa f87  ( .a(c50),    .b(s51),    .cin(s52),    .sum(s97), .cout(c97) );
    fa f88  ( .a(s53),    .b(p14[6]), .cin(p15[5]), .sum(s98), .cout(c98) );
    fa f89  ( .a(c51),    .b(c52),    .cin(c53),    .sum(s99), .cout(c99) );
    fa f90  ( .a(s54),    .b(s55),    .cin(p12[9]), .sum(s100), .cout(c100) );
    fa f91  ( .a(p13[8]), .b(p14[7]), .cin(p15[6]), .sum(s101), .cout(c101) );
    fa f92  ( .a(c54),    .b(c55),    .cin(s56),    .sum(s102), .cout(c102) );
    fa f93  ( .a(p10[12]),.b(p11[11]),.cin(p12[10]),.sum(s103), .cout(c103) );
    fa f94  ( .a(p13[9]), .b(p14[8]), .cin(p15[7]), .sum(s104), .cout(c104) );
    fa f95  ( .a(c56),    .b(p8[15]), .cin(p9[14]),  .sum(s105), .cout(c105) );
    fa f96  ( .a(p10[13]),.b(p11[12]),.cin(p12[11]), .sum(s106), .cout(c106) );
    fa f97  ( .a(p13[10]),.b(p14[9]), .cin(p15[8]),  .sum(s107), .cout(c107) );
    fa f98  ( .a(p9[15]), .b(p10[14]),.cin(p11[13]), .sum(s108), .cout(c108) );
    fa f99  ( .a(p12[12]),.b(p13[11]),.cin(p14[10]), .sum(s109), .cout(c109) );
    fa f100 ( .a(p10[15]),.b(p11[14]),.cin(p12[13]), .sum(s110), .cout(c110) );
    
    //Stage 4 reduction - Dadda
    ha h11  ( .a(p0[4]), .b(p1[3]), .sum(s111), .cout(c111) );
    fa f101 ( .a(p0[5]), .b(p1[4]), .cin(p2[3]), .sum(s112), .cout(c112) );
    ha h12  ( .a(p3[2]), .b(p4[1]), .sum(s113), .cout(c113) );
    fa f102 ( .a(s57),   .b(p2[4]), .cin(p3[3]), .sum(s114), .cout(c114) );
    fa f103 ( .a(p4[2]), .b(p5[1]), .cin(p6[0]), .sum(s115), .cout(c115) );
    fa f104 ( .a(c57),   .b(s58),   .cin(s59),   .sum(s116), .cout(c116) );
    fa f105 ( .a(p5[2]), .b(p6[1]), .cin(p7[0]), .sum(s117), .cout(c117) );
    fa f106 ( .a(c58),   .b(c59),   .cin(s60),   .sum(s118), .cout(c118) );
    fa f107 ( .a(s61),   .b(s62),   .cin(p8[0]), .sum(s119), .cout(c119) );
    fa f108 ( .a(c60),   .b(c61),   .cin(c62),   .sum(s120), .cout(c120) );
    fa f109 ( .a(s63),   .b(s64),   .cin(s65),   .sum(s121), .cout(c121) );
    fa f110 ( .a(c63),   .b(c64),   .cin(c65),   .sum(s122), .cout(c122) );
    fa f111 ( .a(s66),   .b(s67),   .cin(s68),   .sum(s123), .cout(c123) );
    fa f112 ( .a(c66),   .b(c67),   .cin(c68),   .sum(s124), .cout(c124) );
    fa f113 ( .a(s69),   .b(s70),   .cin(s71),   .sum(s125), .cout(c125) );
    fa f114 ( .a(c69),   .b(c70),   .cin(c71),   .sum(s126), .cout(c126) );
    fa f115 ( .a(s72),   .b(s73),   .cin(s74),   .sum(s127), .cout(c127) );
    fa f116 ( .a(c72),   .b(c73),   .cin(c74),   .sum(s128), .cout(c128) );
    fa f117 ( .a(s75),   .b(s76),   .cin(s77),   .sum(s129), .cout(c129) );
    fa f118 ( .a(c75),   .b(c76),   .cin(c77),   .sum(s130), .cout(c130) );
    fa f119 ( .a(s78),   .b(s79),   .cin(s80),   .sum(s131), .cout(c131) );
    fa f120 ( .a(c78),   .b(c79),   .cin(c80),   .sum(s132), .cout(c132) );
    fa f121 ( .a(s81),   .b(s82),   .cin(s83),   .sum(s133), .cout(c133) );
    fa f122 ( .a(c81),   .b(c82),   .cin(c83),   .sum(s134), .cout(c134) );
    fa f123 ( .a(s84),   .b(s85),   .cin(s86),   .sum(s135), .cout(c135) );
    fa f124 ( .a(c84),   .b(c85),   .cin(c86),   .sum(s136), .cout(c136) );
    fa f125 ( .a(s87),   .b(s88),   .cin(s89),   .sum(s137), .cout(c137) );
    fa f126 ( .a(c87),   .b(c88),   .cin(c89),   .sum(s138), .cout(c138) );
    fa f127 ( .a(s90),   .b(s91),   .cin(s92),   .sum(s139), .cout(c139) );
    fa f128 ( .a(c90),   .b(c91),   .cin(c92),   .sum(s140), .cout(c140) );
    fa f129 ( .a(s93),   .b(s94),   .cin(s95),   .sum(s141), .cout(c141) );
    fa f130 ( .a(c93),   .b(c94),   .cin(c95),   .sum(s142), .cout(c142) );
    fa f131 ( .a(s96),   .b(s97),   .cin(s98),   .sum(s143), .cout(c143) );
    fa f132 ( .a(c96),  .b(c97),  .cin(c98),   .sum(s144), .cout(c144) );
    fa f133 ( .a(s99),  .b(s100), .cin(s101),  .sum(s145), .cout(c145) );
    fa f134 ( .a(c99),  .b(c100), .cin(c101),  .sum(s146), .cout(c146) );
    fa f135 ( .a(s102), .b(s103), .cin(s104),  .sum(s147), .cout(c147) );
    fa f136 ( .a(c102), .b(c103), .cin(c104),  .sum(s148), .cout(c148) );
    fa f137 ( .a(s105), .b(s106), .cin(s107),  .sum(s149), .cout(c149) );
    fa f138 ( .a(c105), .b(c106), .cin(c107),  .sum(s150), .cout(c150) );
    fa f139 ( .a(s108), .b(s109), .cin(p15[9]),.sum(s151), .cout(c151) );
    fa f140 ( .a(c108), .b(c109), .cin(s110),  .sum(s152), .cout(c152) );
    fa f141 ( .a(p13[12]), .b(p14[11]), .cin(p15[10]), .sum(s153), .cout(c153) );
    fa f142 ( .a(c110), .b(p11[15]), .cin(p12[14]), .sum(s154), .cout(c154) );
    fa f143 ( .a(p13[13]), .b(p14[12]), .cin(p15[11]), .sum(s155), .cout(c155) );
    fa f144 ( .a(p12[15]), .b(p13[14]), .cin(p14[13]), .sum(s156), .cout(c156) );
    
    //Stage 5 reduction - Dadda
    ha h13  ( .a(p0[3]), .b(p1[2]), .sum(s157), .cout(c157) );
    fa f145 ( .a(s111), .b(p2[2]), .cin(p3[1]), .sum(s158), .cout(c158) );
    fa f146 ( .a(c111), .b(s112), .cin(s113), .sum(s159), .cout(c159) );
    fa f147 ( .a(c112), .b(c113), .cin(s114), .sum(s160), .cout(c160) );
    fa f148 ( .a(c114), .b(c115), .cin(s116), .sum(s161), .cout(c161) );
    fa f149 ( .a(c116), .b(c117), .cin(s118), .sum(s162), .cout(c162) );
    fa f150 ( .a(c118), .b(c119), .cin(s120), .sum(s163), .cout(c163) );
    fa f151 ( .a(c120), .b(c121), .cin(s122), .sum(s164), .cout(c164) );
    fa f152 ( .a(c122), .b(c123), .cin(s124), .sum(s165), .cout(c165) );
    fa f153 ( .a(c124), .b(c125), .cin(s126), .sum(s166), .cout(c166) );
    fa f154 ( .a(c126), .b(c127), .cin(s128), .sum(s167), .cout(c167) );
    fa f155 ( .a(c128), .b(c129), .cin(s130), .sum(s168), .cout(c168) );
    fa f156 ( .a(c130), .b(c131), .cin(s132), .sum(s169), .cout(c169) );
    fa f157 ( .a(c132), .b(c133), .cin(s134), .sum(s170), .cout(c170) );
    fa f158 ( .a(c134), .b(c135), .cin(s136), .sum(s171), .cout(c171) );
    fa f159 ( .a(c136), .b(c137), .cin(s138), .sum(s172), .cout(c172) );
    fa f160 ( .a(c138), .b(c139), .cin(s140), .sum(s173), .cout(c173) );
    fa f161 ( .a(c140), .b(c141), .cin(s142), .sum(s174), .cout(c174) );
    fa f162 ( .a(c142), .b(c143), .cin(s144), .sum(s175), .cout(c175) );
    fa f163 ( .a(c144), .b(c145), .cin(s146), .sum(s176), .cout(c176) );
    fa f164 ( .a(c146), .b(c147), .cin(s148), .sum(s177), .cout(c177) );
    fa f165 ( .a(c148), .b(c149), .cin(s150), .sum(s178), .cout(c178) );
    fa f166 ( .a(c150), .b(c151), .cin(s152), .sum(s179), .cout(c179) );
    fa f167 ( .a(c152), .b(c153), .cin(s154), .sum(s180), .cout(c180) );
    fa f168 ( .a(c154), .b(c155), .cin(s156), .sum(s181), .cout(c181) );
    fa f169 ( .a(c156), .b(p13[15]), .cin(p14[14]), .sum(s182), .cout(c182) );
    
    //Stage 6 reduction - Dadda
    ha h16  ( .a(p0[2]), .b(p1[1]), .sum(s183), .cout(c183) );  
    fa f170 ( .a(s157), .b(p2[1]),  .cin(p3[0]),   .sum(s184), .cout(c184) );
    fa f171 ( .a(c157), .b(s158),   .cin(p4[0]),   .sum(s185), .cout(c185) );
    fa f172 ( .a(c158), .b(s159),   .cin(p5[0]),   .sum(s186), .cout(c186) );
    fa f173 ( .a(c159), .b(s160),   .cin(s115),    .sum(s187), .cout(c187) );
    fa f174 ( .a(c160), .b(s161),   .cin(s117),    .sum(s188), .cout(c188) );
    fa f175 ( .a(c161), .b(s162),   .cin(s119),    .sum(s189), .cout(c189) );
    fa f176 ( .a(c162), .b(s163),   .cin(s121),    .sum(s190), .cout(c190) );
    fa f177 ( .a(c163), .b(s164),   .cin(s123),    .sum(s191), .cout(c191) );
    fa f178 ( .a(c164), .b(s165),   .cin(s125),    .sum(s192), .cout(c192) );
    fa f179 ( .a(c165), .b(s166),   .cin(s127),    .sum(s193), .cout(c193) );
    fa f180 ( .a(c166), .b(s167),   .cin(s129),    .sum(s194), .cout(c194) );
    fa f181 ( .a(c167), .b(s168),   .cin(s131),    .sum(s195), .cout(c195) );
    fa f182 ( .a(c168), .b(s169),   .cin(s133),    .sum(s196), .cout(c196) );
    fa f183 ( .a(c169), .b(s170),   .cin(s135),    .sum(s197), .cout(c197) );
    fa f184 ( .a(c170), .b(s171),   .cin(s137),    .sum(s198), .cout(c198) );
    fa f185 ( .a(c171), .b(s172),   .cin(s139),    .sum(s199), .cout(c199) );
    fa f186 ( .a(c172), .b(s173),   .cin(s141),    .sum(s200), .cout(c200) );
    fa f187 ( .a(c173), .b(s174),   .cin(s143),    .sum(s201), .cout(c201) );
    fa f188 ( .a(c174), .b(s175),   .cin(s145),    .sum(s202), .cout(c202) );
    fa f189 ( .a(c175), .b(s176),   .cin(s147),    .sum(s203), .cout(c203) );
    fa f190 ( .a(c176), .b(s177),   .cin(s149),    .sum(s204), .cout(c204) );
    fa f191 ( .a(c177), .b(s178),   .cin(s151),    .sum(s205), .cout(c205) );
    fa f192 ( .a(c178), .b(s179),   .cin(s153),    .sum(s206), .cout(c206) );
    fa f193 ( .a(c179), .b(s180),   .cin(s155),    .sum(s207), .cout(c207) );
    fa f194 ( .a(c180), .b(s181),   .cin(p15[12]), .sum(s208), .cout(c208) );
    fa f195 ( .a(c181), .b(s182),   .cin(p15[13]), .sum(s209), .cout(c209) );  
    fa f196 ( .a(c182), .b(p14[15]), .cin(p15[14]), .sum(s210), .cout(c210) );
    
    
    //Final stage addiditon completed using Brent kung Adder
    assign in1 = {1'b0, c210, c209, c208, c207, c206, c205, c204, c203, c202, c201, c200, c199, c198, c197, c196, c195, c194, c193, c192, c191, c190, c189, c188, c187, c186, c185, c184, c183, s183, p0[1], p0[0]};
    assign in2 = {1'b1, p15[15], s210, s209, s208, s207, s206, s205, s204, s203, s202, s201, s200, s199, s198, s197, s196, s195, s194, s193, s192, s191, s190, s189, s188, s187, s186, s185, s184, p2[0], p1[0], 1'b0};

    bk_adder_32 bk1 ( .a(in1), .b(in2), .cin(1'b0), .sum(y), .cout());
    


    
endmodule
